#pragma once

enum EggGroups {
	MONSTER_EGG = 0,
	WATER1_EGG = 1,
	BUG_EGG = 2,
	FLYING_EGG = 3,
	FIELD_EGG = 4,
	FAIRY_EGG = 5,
	GRASS_EGG = 6,
	HUMANLIKE_EGG = 7,
	WATER3_EGG = 8,
	MINERAL_EGG = 9,
	AMORPHOUS_EGG = 10,
	WATER2_EGG = 11,
	DITTO_EGG = 12,
	DRAGON_EGG = 13,
	UNDISCOVERD_EGG = 14,
	NONE_EGG = 15
};