#pragma once

enum MoveNames {
	POUND = 0,
	SCRATCH = 1,
	TACKLE = 2,
	GROWL = 3,
	LEER = 4,
	TAIL_WHIP = 5,
	ABSORB = 6,
	EMBER = 7,
	WATER_GUN = 8,
	GRASS_WHISTLE = 9,
	HARDEN = 10,
	MUD_SHOT = 11,
	COPY_CAT = 12,
	RECYCLE = 13,
	BUBBLEBEAM = 14,
	MAGICAL_LEAF = 15,
	FLAME_WHEEL = 16, 
	RAIN_DANCE = 17
};