#pragma once

enum Shape {
	SPERICAL_SHAPE = 0, //only a head
	LEGGED_SHAPE = 1, //head and legs
	FINNED_SHAPE = 2, //with fins
	INSECTOID_SHAPE = 3, 
	QUADRUPED_SHAPE = 4,
	MULTIWINGED_SHAPE = 5,
	MULTIBODY_SHAPE = 6,
	TENTACLE_SHAPE = 7,
	BASED_SHAPE = 8, //Head and Base
	TAILEDBIPED_SHAPE = 9,
	TAILLESSBIPED_SHAPE = 10, 
	WINGED_SHAPE = 11, //single pair of wings
	SERPENTINE_SHAPE = 12,
	ARMED_SHAPE = 13, //head and arms
};

enum Habitat {
	GRASSLAND_HABITAT = 0,
	FOREST_HABITAT = 1,
	SHORE_HABITAT = 2,
	SEA_HABITAT = 3,
	CAVE_HABITAT = 4,
	MOUNTAIN_HABITAT = 5,
	URBAN_HABITAT = 6,
	MARSH_HABITAT = 7,
	DESERT_HABITAT = 8,
	VOLCANO_HABITAT = 9,
	UNKNOWN_HABITAT = 10
};

enum Colour {
	RED_COLOUR = 1,
	BLUE_COLOUR = 2,
	YELLOW_COLOUR = 3,
	GREEN_COLOUR = 4, 
	BLACK_COLOUR = 5,
	BROWN_COLOUR = 6,
	PURPLE_COLOUR = 7,
	GREY_COLOUR = 8,
	WHITE_COLOUR = 9,
	PINK_COLOUR = 10
};