#pragma once

enum NonVolatileStatusNames {
	BURN_NV_STATUS = 0,
	FREEZE_NV_STATUS = 1,
	PARALYSIS_NV_STATUS = 2,
	POISON_NV_STATUS = 3,
	BAD_POISON_NV_STATUS = 4,
	SLEEP_NV_STATUS = 5,
	FLUX_NV_STATUS = 6
};